# Generated by Django 4.1.7 on 2023-02-28 17:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(db_column='flight_number', max_length=256)),
                ('origin_country', models.CharField(db_column='origin_country', max_length=256)),
                ('origin_city', models.CharField(db_column='origin_city', max_length=256)),
                ('origin_airport_code', models.CharField(db_column='origin_airport_code', max_length=256)),
                ('destination_country', models.CharField(db_column='destination_country', max_length=256)),
                ('destination_city', models.CharField(db_column='destination_city', max_length=256)),
                ('destination_airport_code', models.CharField(db_column='destination_airport_code', max_length=256)),
                ('origin_datetime', models.DateTimeField(db_column='origin_datetime')),
                ('destination_datetime', models.DateTimeField(db_column='destination_datetime')),
                ('total_seats', models.IntegerField(db_column='total_seats', validators=[django.core.validators.MinValueValidator(0)])),
                ('seats_left', models.IntegerField(db_column='seats_left', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_cancelled', models.BooleanField(db_column='is_cancelled')),
                ('price', models.FloatField(db_column='price')),
            ],
            options={
                'db_table': 'flights',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField(db_column='num_seats')),
                ('order_date', models.DateField(auto_now=True, db_column='order_date')),
                ('total_price', models.FloatField(db_column='total_price')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='flights_app.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
